import { FormEvent,useEffect,useState } from "react";
import { createPortalUser,deletePortalUser,getPortalUsers,updatePortalUser } from "../services/api";
import type { PortalUser,Role } from "../types";
export default function AdminPage({token,username}:{token:string;username:string}){
 const [users,setUsers]=useState<PortalUser[]>([]),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[role,setRole]=useState<Role>("developer"),[admin,setAdmin]=useState(false);
 const load=()=>getPortalUsers(token).then(setUsers).catch(e=>setError(e instanceof Error?e.message:"Unable to load users")); useEffect(()=>{void load();},[token]);
 async function add(e:FormEvent){e.preventDefault();setError("");setNotice("");if(!email.toLowerCase().endsWith("@mashreq.com"))return setError("User ID must end with @mashreq.com");setBusy(true);try{await createPortalUser({email,password,role,is_admin:admin},token);setEmail("");setPassword("");setRole("developer");setAdmin(false);setNotice("User created successfully.");await load();}catch(x){setError(x instanceof Error?x.message:"Unable to create user");}finally{setBusy(false);}}
 async function change(user:PortalUser,patch:Partial<PortalUser>){setBusy(true);setError("");try{await updatePortalUser(user.id,{role:(patch.role??user.role),is_admin:patch.is_admin??user.is_admin,is_active:patch.is_active??user.is_active},token);await load();}catch(x){setError(x instanceof Error?x.message:"Unable to update user");}finally{setBusy(false);}}
 async function remove(user:PortalUser){if(!window.confirm(`Delete ${user.email}?`))return;setBusy(true);try{await deletePortalUser(user.id,token);await load();}catch(x){setError(x instanceof Error?x.message:"Unable to delete user");}finally{setBusy(false);}}
 return <section><div className="section-heading"><div><span className="eyebrow">DEVOPS ADMIN</span><h2>User Management</h2><p>Create and manage portal access. Only DevOps administrators can access these controls.</p></div></div>{error&&<div className="form-error">{error}</div>}{notice&&<div className="form-success">{notice}</div>}
 <form className="form-card two-column" onSubmit={add}><label>User ID<input type="email" required value={email} placeholder="name@mashreq.com" onChange={e=>setEmail(e.target.value)}/></label><label>Temporary Password<input type="password" minLength={10} required value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Role<select value={role} onChange={e=>{const r=e.target.value as Role;setRole(r);if(r!=="devops")setAdmin(false);}}><option value="developer">Developer</option><option value="devops">DevOps</option></select></label><label className="checkbox-line"><input type="checkbox" disabled={role!=="devops"} checked={admin} onChange={e=>setAdmin(e.target.checked)}/>DevOps Administrator</label><div className="full-width"><button className="primary-button" disabled={busy}>Add User</button></div></form>
 <div className="table-card" style={{marginTop:24}}><table><thead><tr><th>User ID</th><th>Role</th><th>Admin</th><th>Status</th><th>Actions</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><strong>{u.email}</strong>{u.email===username&&<small> (you)</small>}</td><td><select disabled={busy} value={u.role} onChange={e=>change(u,{role:e.target.value as Role,is_admin:e.target.value==="devops"?u.is_admin:false})}><option value="developer">Developer</option><option value="devops">DevOps</option></select></td><td><input type="checkbox" disabled={busy||u.role!=="devops"} checked={u.is_admin} onChange={e=>change(u,{is_admin:e.target.checked})}/></td><td><button className="secondary-button compact-button" disabled={busy} onClick={()=>change(u,{is_active:!u.is_active})}>{u.is_active?"Active":"Inactive"}</button></td><td><button className="danger-button compact-button" disabled={busy||u.email===username} onClick={()=>remove(u)}>Delete</button></td></tr>)}</tbody></table></div></section>;
}
