import {FormEvent,useEffect,useState} from "react";
import {commentDevOpsTask,createDevOpsTask,getDevOpsTasks,getPortalUsers,reassignDevOpsTask,updateDevOpsTask} from "../services/api";
import type {DevOpsTask,DevOpsTaskStatus,PortalUser} from "../types";
const statusLabel={backlog:"Backlog",inprogress:"In Progress",completed:"Completed"};
export default function DevOpsTasksPage({token,username,isAdmin}:{token:string;username:string;isAdmin:boolean}){
 const current=new Date().toISOString().slice(0,7);const[tasks,setTasks]=useState<DevOpsTask[]>([]),[users,setUsers]=useState<PortalUser[]>([]),[selected,setSelected]=useState<DevOpsTask|null>(null),[error,setError]=useState(""),[month,setMonth]=useState(current),[status,setStatus]=useState(""),[assignee,setAssignee]=useState(""),[search,setSearch]=useState(""),[start,setStart]=useState(""),[end,setEnd]=useState("");const[title,setTitle]=useState(""),[description,setDescription]=useState(""),[newAssignee,setNewAssignee]=useState(username),[comment,setComment]=useState("");
 const load=async()=>{try{setError("");setTasks(await getDevOpsTasks(token,{month:start||end?"":month,status,assignee,q:search,start_date:start,end_date:end}));if(isAdmin)setUsers((await getPortalUsers(token)).filter(u=>u.role==="devops"&&u.is_active));}catch(e){setError(e instanceof Error?e.message:"Unable to load tasks")}};useEffect(()=>{void load()},[token,month,status,assignee,start,end]);
 async function create(e:FormEvent){e.preventDefault();try{await createDevOpsTask({title,description,assignee:newAssignee},token);setTitle("");setDescription("");await load()}catch(x){setError(x instanceof Error?x.message:"Unable to create task")}}
 async function update(t:DevOpsTask,p:{status?:DevOpsTaskStatus;title?:string;description?:string}){try{const v=await updateDevOpsTask(t.id,p,token);setSelected(v);await load()}catch(x){setError(x instanceof Error?x.message:"Unable to update task")}}
 async function addComment(){if(!selected||!comment.trim())return;try{const v=await commentDevOpsTask(selected.id,comment,token);setSelected(v);setComment("");await load()}catch(x){setError(x instanceof Error?x.message:"Unable to add comment")}}
 const canEdit=(t:DevOpsTask)=>isAdmin||t.assignee.toLowerCase()===username.toLowerCase();
 return <section><div className="section-heading"><div><span className="eyebrow">DEVOPS WORK MANAGEMENT</span><h2>DevOps Tasks</h2><p>Monthly backlog, active work and completed tasks with assignment history and comments.</p></div></div>{error&&<div className="form-error">{error}</div>}
 <form className="form-card two-column" onSubmit={create}><label>Task title<input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="Task title"/></label><label>Assignee>{isAdmin?<select value={newAssignee} onChange={e=>setNewAssignee(e.target.value)}>{users.map(u=><option key={u.id}>{u.email}</option>)}</select>:<input value={username} readOnly/>}</label><label className="full-width">Description<textarea required rows={3} value={description} onChange={e=>setDescription(e.target.value)}/></label><div className="full-width"><button className="primary-button">Create Task</button></div></form>
 <div className="form-card" style={{marginTop:20}}><div className="filter-grid"><label>Month<input type="month" value={month} onChange={e=>{setMonth(e.target.value);setStart("");setEnd("")}}/></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All</option><option value="backlog">Backlog</option><option value="inprogress">In Progress</option><option value="completed">Completed</option></select></label><label>Assignee<input value={assignee} onChange={e=>setAssignee(e.target.value)} placeholder="user@mashreq.com"/></label><label>Search title / details<input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();void load()}}}/></label><label>From<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>To<input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label><button className="secondary-button" onClick={()=>void load()}>Search</button></div></div>
 <div className="task-board">{(["backlog","inprogress","completed"] as DevOpsTaskStatus[]).map(s=><div className="task-column" key={s}><h3>{statusLabel[s]} <span>{tasks.filter(t=>t.status===s).length}</span></h3>{tasks.filter(t=>t.status===s).map(t=><button className="task-card" key={t.id} onClick={()=>setSelected(t)}><small>{t.id}</small><strong>{t.title}</strong><p>{t.description}</p><span>{t.assignee}</span><time>{new Date(t.updated_at).toLocaleString()}</time></button>)}</div>)}</div>
 {selected&&<div className="modal-backdrop"><div className="modal-card"><button className="modal-close" onClick={()=>setSelected(null)}>×</button><span className="eyebrow">{selected.id}</span><input className="task-title-input" defaultValue={selected.title} disabled={!canEdit(selected)} onBlur={e=>e.target.value!==selected.title&&update(selected,{title:e.target.value})}/><textarea rows={5} defaultValue={selected.description} disabled={!canEdit(selected)} onBlur={e=>e.target.value!==selected.description&&update(selected,{description:e.target.value})}/><div className="filter-grid"><label>Status<select disabled={!canEdit(selected)} value={selected.status} onChange={e=>update(selected,{status:e.target.value as DevOpsTaskStatus})}>{Object.entries(statusLabel).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>{isAdmin&&<label>Reassign<select value={selected.assignee} onChange={async e=>{const v=await reassignDevOpsTask(selected.id,e.target.value,token);setSelected(v);await load()}}>{users.map(u=><option key={u.id}>{u.email}</option>)}</select></label>}</div><h3>Comments</h3><div className="comments">{selected.comments.map(c=><div key={c.id}><strong>{c.author}</strong><small>{new Date(c.created_at).toLocaleString()}</small><p>{c.text}</p></div>)}</div>{canEdit(selected)&&<div className="comment-box"><textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder="Add a comment..."/><button className="primary-button" onClick={addComment}>Add Comment</button></div>}<h3>History</h3>{selected.history.slice().reverse().map((h,i)=><p key={i} className="history-line"><strong>{h.actor}</strong> · {h.action} · {new Date(h.at).toLocaleString()}</p>)}</div></div>}
 </section>}
