import GtbAgentPage from "./pages/GtbAgentPage";
import { useEffect,useMemo,useState } from "react";
import { BarChart3,Bot,Boxes,ClipboardList,FileUp,Home,ListTodo,LogOut,Menu,Rocket,Search,ShieldCheck } from "lucide-react";
import type {AuthSession,NavItem,PageKey} from "./types"; import LoginPage from "./pages/LoginPage"; import HomePage from "./pages/HomePage"; import DashboardPage from "./pages/DashboardPage"; import RequestsPage from "./pages/RequestsPage"; import FilePlacementPage from "./pages/FilePlacementPage"; import MonitoringPage from "./pages/MonitoringPage"; import DeploymentManagementPage from "./pages/DeploymentManagementPage"; import MsPortalPage from "./pages/MsPortalPage"; import AdminPage from "./pages/AdminPage"; import DevOpsTasksPage from "./pages/DevOpsTasksPage"; import NotificationCenter from "./components/NotificationCenter";
const BASE_PATH="/devops-portal";
const navItems:NavItem[]=[{key:"gtb-agent",label:"GTB Operations Agent",devopsOnly:true},{key:"home",label:"Home"},{key:"dashboard",label:"Dashboard"},{key:"ms-portal",label:"New Pipeline Request"},{key:"requests",label:"Pipeline Requests"},{key:"deployment-management",label:"Deployment Management"},{key:"devops-tasks",label:"DevOps Tasks",devopsOnly:true},{key:"file-placement",label:"File Placement",href:"/devops-portal/file-placement/"},{key:"monitoring",label:"Monitoring",devopsOnly:true},{key:"admin",label:"Admin",devopsOnly:true,adminOnly:true}];
const icons={"gtb-agent":Bot,home:Home,dashboard:BarChart3,requests:ClipboardList,"file-placement":FileUp,monitoring:Boxes,"deployment-management":Rocket,"ms-portal":Boxes,"devops-tasks":ListTodo,admin:ShieldCheck};
const pagePaths:Record<PageKey,string>={"gtb-agent":`${BASE_PATH}/gtb-agent`,home:`${BASE_PATH}/home`,dashboard:`${BASE_PATH}/dashboard`,requests:`${BASE_PATH}/requests`,"file-placement":`${BASE_PATH}/file-placement/`,monitoring:`${BASE_PATH}/monitoring`,"deployment-management":`${BASE_PATH}/deployment-management`,"ms-portal":`${BASE_PATH}/request/new`,"devops-tasks":`${BASE_PATH}/devops-tasks`,admin:`${BASE_PATH}/admin`};
function pageFromPath(p:string):PageKey{const n=p.replace(/\/+$/,"")||"/";for(const [k,v] of Object.entries(pagePaths))if(n===v.replace(/\/+$/,""))return k as PageKey;return "home";}
function readStoredSession():AuthSession|null{const raw=sessionStorage.getItem("devops-session");if(!raw)return null;try{return JSON.parse(raw)}catch{sessionStorage.removeItem("devops-session");return null;}}
export default function App(){const[session,setSession]=useState<AuthSession|null>(readStoredSession),[page,setPage]=useState<PageKey>(()=>pageFromPath(window.location.pathname)),[query,setQuery]=useState(""),[collapsed,setCollapsed]=useState(false),[refreshKey,setRefreshKey]=useState(0);
 const visibleItems=useMemo(()=>navItems.filter(i=>(!i.devopsOnly||session?.role==="devops")&&(!i.adminOnly||session?.is_admin)),[session]); const filteredItems=visibleItems.filter(i=>i.label.toLowerCase().includes(query.toLowerCase()));
 useEffect(()=>{const h=()=>{if(!session){window.history.replaceState({},"",`${BASE_PATH}/login`);return;}const next=pageFromPath(window.location.pathname);setPage((next==="admin"&&!session.is_admin)||((next==="devops-tasks"||next==="gtb-agent")&&session.role!=="devops")?"home":next)};window.addEventListener("popstate",h);return()=>window.removeEventListener("popstate",h)},[session]);
 useEffect(()=>{if(!session){if(window.location.pathname!==`${BASE_PATH}/login`)window.history.replaceState({},"",`${BASE_PATH}/login`);return;}if(window.location.pathname===`${BASE_PATH}/login`){window.history.replaceState({},"",pagePaths.home);setPage("home");}if((page==="admin"&&!session.is_admin)||((page==="devops-tasks"||page==="gtb-agent")&&session.role!=="devops")){window.history.replaceState({},"",pagePaths.home);setPage("home");}},[session,page]);
 function completeLogin(s:AuthSession){sessionStorage.setItem("devops-session",JSON.stringify(s));setSession(s);setPage("home");window.history.replaceState({},"",pagePaths.home)} function logout(){sessionStorage.removeItem("devops-session");setSession(null);setPage("home");window.history.replaceState({},"",`${BASE_PATH}/login`)} function changePage(p:PageKey){if((p==="admin"&&!session?.is_admin)||((p==="devops-tasks"||p==="gtb-agent")&&session?.role!=="devops"))return;setPage(p);window.history.pushState({},"",pagePaths[p])} function navigate(i:NavItem){setQuery("");if(i.href){window.location.assign(i.href);return;}changePage(i.key)}
 if(!session)return <LoginPage onLogin={completeLogin}/>;
 const renderPage=()=>({"gtb-agent":session.role==="devops"?<GtbAgentPage token={session.access_token}/>:null,home:<HomePage onNavigate={changePage}/>,dashboard:<DashboardPage token={session.access_token} role={session.role} refreshKey={refreshKey}/>,requests:<RequestsPage token={session.access_token} role={session.role} refreshKey={refreshKey}/>,"file-placement":<FilePlacementPage/>,monitoring:<MonitoringPage token={session.access_token}/>,"deployment-management":<DeploymentManagementPage token={session.access_token} role={session.role}/>,"ms-portal":<MsPortalPage token={session.access_token} onCreated={()=>setRefreshKey(v=>v+1)}/>,"devops-tasks":<DevOpsTasksPage token={session.access_token} username={session.username} isAdmin={session.is_admin}/>,admin:<AdminPage token={session.access_token} username={session.username}/>})[page];
 return <div className={`app-shell ${collapsed?"sidebar-collapsed":""}`}><aside className="sidebar"><div className="brand"><div className="brand-mark">N</div><div className="brand-copy"><strong>NEO CORP</strong><span>DEVOPS</span></div></div><button className="collapse-button" onClick={()=>setCollapsed(v=>!v)}><Menu size={20}/></button><nav>{visibleItems.map(i=>{const Icon=icons[i.key];return <button key={i.key} className={!i.href&&page===i.key?"nav-item active":"nav-item"} onClick={()=>navigate(i)}><Icon size={20}/><span>{i.label}</span></button>})}</nav><div className="sidebar-footer"><div className="user-avatar">{session.username.slice(0,2).toUpperCase()}</div><div><strong>{session.username}</strong><span>{session.is_admin?"DevOps Admin":session.role==="devops"?"DevOps":"Developer"}</span></div></div></aside><main className="main-area"><header className="topbar"><div className="search-wrap"><Search size={20}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search tasks, services and requests..."/>{query&&<div className="search-results">{filteredItems.map(i=><button key={i.key} onClick={()=>navigate(i)}>{i.label}</button>)}</div>}</div><div className="topbar-actions"><NotificationCenter token={session.access_token} role={session.role} username={session.username} refreshKey={refreshKey} onOpenRequests={()=>changePage("requests")}/><span className="role-badge">{session.is_admin?"DevOps Admin":session.role==="devops"?"DevOps":"Developer"}</span><button className="icon-button" onClick={logout}><LogOut size={20}/></button></div></header><div className="content">{renderPage()}</div></main></div>}
